version: '2'
services:
    sampledownload-app:
        image: sampledownload
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sampledownload-mysql:3306/sampledownload?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 9100:9100
    sampledownload-mysql:
        extends:
            file: mysql.yml
            service: sampledownload-mysql
